version: '3.8'

services:
  go-app:
    image: golang:1.23
    container_name: go-app
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080

volumes:
  postgres_data:
