services:
  go-app:
    image: golang:1.23-alpine
    container_name: go-app
    working_dir: /app/snap-go
    build:
      context: .
    volumes:
      - ./snap-go:/app/snap-go  # Ensure this path points to the right directory
      - /app/snap-go/tmp
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
