services:
  go-app:
    image: golang:1.23.1
    container_name: go-app
    volumes:
      - ./snap-go:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
