services:
  - type: web
    name: snap
    plan: free
    buildCommand: cd snap-go && go build -o server
    startCommand: ./snap-go/server
    region: frankfurt
    autoDeploy: true
    runtime: go
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: 8080