services:
  - type: web
    name: go-simple-server
    env: go
    plan: free
    buildCommand: go build -o server
    startCommand: ./server
    region: oregon
    autoDeploy: true
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: 8080
